services:
  university_db:
    image: postgres:16
    container_name: university_db
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: Cascaval2024#
      POSTGRES_DB: university
    ports:
      - "5434:5432"
    volumes:
      - university_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - university_db

volumes:
  message_broker_data:
  university_data: